### ISSUE TITLE
1.2.2 works, 1.2.3 does not.

### ISSUE THREAD

**Issue by Baddest-Juju** [Xebeth/xcom2-launcher#2]
1.2.3 throws an error regarding SteamWorks.

```
Could not load file or assembly 'Steamworks.NET, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
Stack:
   at XCOM2Launcher.Classes.Steam.SteamAPIWrapper.Init()
   at XCOM2Launcher.Program.Main()
```

**Comment by Xebeth** [comment]
Thanks for reporting this. I don't know how I missed that... I've reuploaded release 1.2.3 without SNK.
